### PR TITLE
add pink theme, convert hard-coded color names to variables

### PR DESCRIPTION
**Pull request by rio-codes**
I created a pink palette and mode for risotto. I also modified logo.css and typography.css to use variables instead of hard-coded colors from the existing palettes, making it easier to add new palettes and modes in the future. Finally, I changed the existing dark and light mode files to use the original colors.

### CODE REVIEW

**Comment by rio-codes** [comment]
I know this hasn't been approved yet but do you mind if I start working on one of the existing issues?

**Comment by joeroe** [comment]
Please go ahead. I'll review this as soon as I can :)

**Comment by rio-codes** [comment]
Cool. Is there an existing issue that needs some love? I could maybe tackle #6 ?

**Comment by rio-codes** [comment]
Hi, I was wondering if you mind if I start another theme for this? I've been working on this [Catppuccin](https://github.com/catppuccin/catppuccin) palette project and I'd love to make a risotto theme for it. If you don't like this pink one you can cancel it, but it would be nice to have the changes to the variables in it, maybe a separate PR?

**Comment by rio-codes** [comment]
Breaking variable changes off into new PR.

**Comment by joeroe** [comment]
@rio-codes Sorry for the slow response. Both the pink and Catppuccin palettes are very welcome, if you still want to contribute them?

**Pull request closed without merging**
